### PR TITLE
use block instead of inline for span to apply the background color co…

### PR DESCRIPTION
**Pull request by michael8090**
…rrectly for multiple line text; fix the top (100px -> 108px)

### CODE REVIEW

**Comment by michael8090** [comment]
fix styles for multiple line text

**Comment by ryohey** [comment]
why this wouldn't be merged?

**Comment by jesusoterogomez** [comment]
I want to make an improvement where the vertical size and positioning is dynamic, are you sure substracting 8px from the top value doesn't affect 1 lined messages?.

I will try to test this out and merge it if appropriate, but the hardcoded positioning will probably be based on content later on.

**Comment by jesusoterogomez** [comment]
I'm closing this PR due to it being no longer valid. The proposed fix was implemented in another way that doesn't require the module having a hardcoded size, as mentioned in my previous (ancient) comment 😆

**Pull request closed without merging**
