### PR TITLE
custom colors

### PR DESCRIPTION
**Pull request by donsalari**
set your custom color:
`notify.show("this is sample text", "custom", 5000, {background: '#0E1717', text: "#FFFFFF"});`

### CODE REVIEW

**Comment by donsalari** [comment]
Sure! no worries. Ill update the readme.

**Comment by donsalari** [comment]
hey @jesusoterogomez, could you please publish a new the version?

**Comment by jesusoterogomez** [comment]
Sorry @donsalari . I thought I had already automated it in travis. I realized it was just a dream :). I just released `v0.1.4`

**Comment by donsalari** [comment]
thanks man! really appreciate it.

**Pull request merged**
