### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by jchip**
object-assign@4: Faster and preserves property order

### CODE REVIEW

**Comment by jesusoterogomez** [comment]
This will be available on the next version (0.4.1)

**Comment by jchip** [comment]
@jesusoterogomez could you publish the next version please?  thanks.

**Comment by jesusoterogomez** [comment]
I'm on it! sorry for not doing it earlier :)

**Comment by jesusoterogomez** [comment]
@jchip It's done! Have a great day!

**Comment by jchip** [comment]
thank you.

**Pull request merged**
